---
name: horae
version: 070
author:
  - 'Bruce Ravel <bravel AT bnl DOT gov>'
abstract: XAS data processing and analysis using Ifeffit
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Zip: 0
  Chemistry::Elements: 0
  Compress::Zlib: 0
  Config::IniFiles: 0
  Math::Combinatorics: 0
  Math::Derivative: 0
  Math::Round: 0
  Math::Spline: 0
  Parse::RecDescent: 0
  Pod::Escapes: 0
  Pod::Simple: 0
  Spreadsheet::WriteExcel: 0
  Statistics::Descriptive: 0
  Text::Glob: 0
  Tie::IxHash: 0
  Tie::Watch: 0
  Time::Stopwatch: 0
  Tk: 804.027
  Tk::FileDialog: 0
  Tk::HistEntry: 0
  Tk::NumEntry: 0
  Tk::Pod: 0
  Tk::Splashscreen: 0
provides:
  Ifeffit::ArtemisLog:
    file: lib/Ifeffit/ArtemisLog.pm
    version: 0.8.013
  Ifeffit::Elements:
    file: lib/Ifeffit/Elements.pm
    version: 0.00
  Ifeffit::Files:
    file: lib/Ifeffit/Files.pm
  Ifeffit::FindFile:
    file: lib/Ifeffit/FindFile.pm
  Ifeffit::Group:
    file: lib/Ifeffit/Group.pm
    version: 0.8.059
  Ifeffit::Parameter:
    file: lib/Ifeffit/Parameter.pm
    version: 0.8.013
  Ifeffit::ParseFeff:
    file: lib/Ifeffit/ParseFeff.pm
  Ifeffit::Path:
    file: lib/Ifeffit/Path.pm
    version: 0.8.013
  Ifeffit::Plugins::Filetype::Athena::BESSRC:
    file: lib/Ifeffit/Plugins/Filetype/Athena/BESSRC.pm
  Ifeffit::Plugins::Filetype::Athena::CMC:
    file: lib/Ifeffit/Plugins/Filetype/Athena/CMC.pm
  Ifeffit::Plugins::Filetype::Athena::Encoder:
    file: lib/Ifeffit/Plugins/Filetype/Athena/Encoder.pm
  Ifeffit::Plugins::Filetype::Athena::HXMA:
    file: lib/Ifeffit/Plugins/Filetype/Athena/HXMA.pm
  Ifeffit::Plugins::Filetype::Athena::Lambda:
    file: lib/Ifeffit/Plugins/Filetype/Athena/Lambda.pm
  Ifeffit::Plugins::Filetype::Athena::PFBL12C:
    file: lib/Ifeffit/Plugins/Filetype/Athena/PFBL12C.pm
  Ifeffit::Plugins::Filetype::Athena::SSRLA:
    file: lib/Ifeffit/Plugins/Filetype/Athena/SSRL.pm
  Ifeffit::Plugins::Filetype::Athena::SSRLB:
    file: lib/Ifeffit/Plugins/Filetype/Athena/SSRLB.pm
  Ifeffit::Plugins::Filetype::Athena::SSRLmicro:
    file: lib/Ifeffit/Plugins/Filetype/Athena/SSRLmicro.pm
  Ifeffit::Plugins::Filetype::Athena::X10C:
    file: lib/Ifeffit/Plugins/Filetype/Athena/X10C.pm
  Ifeffit::Plugins::Filetype::Athena::X15B:
    file: lib/Ifeffit/Plugins/Filetype/Athena/X15B.pm
  Ifeffit::Tools:
    file: lib/Ifeffit/Tools.pm
    version: 070
  STAR::Checker:
    file: lib/STAR/Checker.pm
    version: 0.02
  STAR::DataBlock:
    file: lib/STAR/DataBlock.pm
    version: 0.58
  STAR::Dictionary:
    file: lib/STAR/Dictionary.pm
    version: 0.56
  STAR::Filter:
    file: lib/STAR/Filter.pm
    version: 0.01
  STAR::Parser:
    file: lib/STAR/Parser.pm
    version: 0.59
  STAR::Writer:
    file: lib/STAR/Writer.pm
    version: 0.01
  Tk::KeyEntry:
    file: lib/Tk/KeyEntry.pm
  Tk::PathparamEntry:
    file: lib/Tk/PathparamEntry.pm
  Tk::RetEntry:
    file: lib/Tk/RetEntry.pm
  Tk::TextUndoQuiet:
    file: lib/Tk/TextUndoQuiet.pm
  WWWBrowser:
    file: lib/WWWBrowser.pm
    version: 2.23
  Xray::ATP:
    file: lib/Xray/ATP.pm
    version: 0
  Xray::Atoms:
    file: lib/Xray/Atoms.pm
    version: 3.0
  Xray::Tk::SGB:
    file: lib/Xray/Tk/SGB.pm
    version: 0.03
  Xray::Xtal:
    file: lib/Xray/Xtal.pm
    version: 0.31
  Xray::Xtal::Cell:
    file: lib/Xray/Xtal.pm
  Xray::Xtal::Site:
    file: lib/Xray/Xtal.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
